### ISSUE TITLE
High CPU Usage during attack phase

### ISSUE THREAD

**Issue by agoschie** [cs361fall2018/project-team39#17]
I suspect that there is a hanging loop. Possibly due to /attack request activating the following code segment:
` 
do {
            // AI does random attacks, so it might attack the same spot twice
            // let it try until it gets it right
            opponentAttackResult = playersBoard.attack(randRow(1, this.sizeRow), randCol('A', (char) (this.sizeColumn + 64)));
        } while(opponentAttackResult.getResult() != INVALID);
`

**Comment by radiian** [comment]
Random() is not seeded with a non constant value which may lead to predictable patterns in random generation. It's possible that it's using the same random path over and over every time the program is rerun. Suggest seeding the random function with the current time stamp for best results.

**Comment by agoschie** [comment]
I'm pretty sure `!=` should be `==`, and I will test it. However, we should consider this apart of #1  and #11, and thus I am assigning it to you radiian.

**Comment by radiian** [comment]
I misspoke, the attack procedure currently returns an empty attack result so the code will be unstable. Once the procedure is fully implemented then we should reevaluate the attack loop.

**Comment by Simouie** [comment]
This bug has been resolved.
