### ISSUE TITLE
Round counter system

### ISSUE THREAD

**Issue by agoschie** [cs361fall2018/project-team39#34]
There needs to be a Round: number style counter on the right side of the document . It needs to be prominent. Don't be fooled into thinking this is a simple feature, it needs re-instancing of the game.

**1.** After you win or lose a game, the round counter should be incremented and a new game should begin.
**2.** This requires re-instancing the game in some way.

**Comment by radiian** [comment]
This seems like it would benefit from being split into two separate issues. One issue to count the rounds, and another issue to restart the game on a win or loss. Thoughts?

**Comment by radiian** [comment]
Feature complete and merged into master. Closing the issue.
