### ISSUE TITLE
Refactor front end code and fix UI

### ISSUE THREAD

**Issue by Simouie** [cs361fall2018/project-team39#41]
The first objective to optimize the code for the front end.
This will include:
- making it less verbose and cleaner overall
- organizing chunks of code so that they are grouped together if related
- slightly changing names to make all of them follow the same general style

The second objective is to fix parts of the UI that were not completely finished in Sprint 2.
This will include:
- the positioning and styling of the message box
- the positioning and styling of the round counter
- the positioning of the grids and related elements
- the positioning and styling of the ship placement elements

These two objectives are grouped together, as they are best done at the same time rather than separately, to avoid merge conflicts and inconsistencies.

**Comment by agoschie** [comment]
Is this feature officially taken care of?

**Comment by Simouie** [comment]
I plan to make a few more small changes
