### ISSUE TITLE
Refactor back end code

### ISSUE THREAD

**Issue by Simouie** [cs361fall2018/project-team39#42]
The objective is reorganize and modify the code for the back end. The goal is to make it easier to work with and expand upon for Sprint 3 and Sprint 4 features, and make it better fit object oriented design.

Refactoring for the back end code will include:
- turning the various ship types into subclasses of the Ship class
- adding support for subclasses of Ship in Game class
- distributing some of the responsibilities of the Board class to the Ship class and its subclasses

**Comment by agoschie** [comment]
As of now, the issue has been taken care of since the merging of #43 . If there are any new bugs that were unforseen, and additional fixes to the refactor are required, we can open this issue back up. But as of now, its solved.
