### ISSUE TITLE
Move laser weapon and normal attack into weapons class hierarchy (refactor)

### ISSUE THREAD

**Issue by agoschie** [cs361fall2018/project-team39#62]
The laser weapon and normal attacks should be either turned into derived classes of a single weapons class, or added to the weapons class directly. Dont overcomplicate the code. For instance, the laser should probably just attack both the surface and submerged board, while the normal attack should only attack the surface board. Put the instances of the weapon in commander and add some usage code (i.e. commander.fireLaser)

**Comment by OllyTheBug** [comment]
Resolved
